# Generated by Django 5.2 on 2025-04-29 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(choices=[('oddiy', 'Oddiy'), ('diler', 'Diler')], max_length=6)),
                ('phone', models.CharField(max_length=16)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('location', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company-logo/')),
                ('website', models.URLField()),
                ('address', models.TextField()),
                ('is_verified', models.BooleanField()),
                ('rating', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
