# Generated by Django 5.2 on 2025-05-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_user_alter_dealer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('dealer', 'Dealer')], max_length=7),
        ),
    ]
