# Generated by Django 5.2 on 2025-05-03 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodytype',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_type', to='cars.image'),
        ),
    ]
