# Generated by Django 5.2 on 2025-05-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_bodytype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drive_type',
            field=models.CharField(choices=[('FWD', 'Front-Wheel Drive'), ('RWD', 'Rear-Wheel Drive'), ('AWD', 'All-Wheel Drive')], max_length=50),
        ),
    ]
